name = "Horizontal Backpropagator"

[files]
"https://raw.githubusercontent.com/tuftsceeo/spike-neural-nets/refs/heads/main/TeachingNNs/horizontal-backpropagator/state.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/spike-neural-nets/refs/heads/main/TeachingNNs/horizontal-backpropagator/activations.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/spike-neural-nets/refs/heads/main/TeachingNNs/horizontal-backpropagator/network_model.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/spike-neural-nets/refs/heads/main/TeachingNNs/horizontal-backpropagator/diagram_render.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/spike-neural-nets/refs/heads/main/TeachingNNs/horizontal-backpropagator/dataset_ui.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/spike-neural-nets/refs/heads/main/TeachingNNs/horizontal-backpropagator/plots.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/spike-neural-nets/refs/heads/main/TeachingNNs/horizontal-backpropagator/training.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/spike-neural-nets/refs/heads/main/TeachingNNs/horizontal-backpropagator/ui_refresh.py" = ""
