packages = ["plotly"]

name = "Gradient Descent Visualization"

[files]
"https://raw.githubusercontent.com/tuftsceeo/spike-neural-nets/refs/heads/main/TeachingNNs/gradient-descent-visualization/main.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/spike-neural-nets/refs/heads/main/TeachingNNs/gradient-descent-visualization/state.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/spike-neural-nets/refs/heads/main/TeachingNNs/gradient-descent-visualization/flowchart.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/spike-neural-nets/refs/heads/main/TeachingNNs/gradient-descent-visualization/dom.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/spike-neural-nets/refs/heads/main/TeachingNNs/gradient-descent-visualization/math_core.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/spike-neural-nets/refs/heads/main/TeachingNNs/gradient-descent-visualization/plots.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/spike-neural-nets/refs/heads/main/TeachingNNs/gradient-descent-visualization/app.py" = ""
