name = "network-builder"
packages = [ "legoeducation","numpy"]

[files]
"https://raw.githubusercontent.com/tuftsceeo/spike-neural-nets/refs/heads/main/TeachingNNs/network-builder/glue/bindings.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/spike-neural-nets/refs/heads/main/TeachingNNs/network-builder/glue/state.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/spike-neural-nets/refs/heads/main/TeachingNNs/network-builder/glue/sync.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/spike-neural-nets/refs/heads/main/TeachingNNs/network-builder/network/activation_editor.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/spike-neural-nets/refs/heads/main/TeachingNNs/network-builder/network/activations.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/spike-neural-nets/refs/heads/main/TeachingNNs/network-builder/network/network_actions.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/spike-neural-nets/refs/heads/main/TeachingNNs/network-builder/network/network_model.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/spike-neural-nets/refs/heads/main/TeachingNNs/network-builder/Device.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/spike-neural-nets/refs/heads/main/TeachingNNs/network-builder/plot.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/spike-neural-nets/refs/heads/main/TeachingNNs/network-builder/main.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/spike-neural-nets/refs/heads/main/TeachingNNs/network-builder/misc_ui/arrows.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/spike-neural-nets/refs/heads/main/TeachingNNs/network-builder/misc_ui/templates.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/spike-neural-nets/refs/heads/main/TeachingNNs/network-builder/misc_ui/zoom.py" = ""

[js_modules.main]
"https://cdn.jsdelivr.net/gh/tuftsceeo/spike-neural-nets@main/TeachingNNs/network-builder/JS/ble.js" = "ble"
"https://cdn.jsdelivr.net/gh/tuftsceeo/spike-neural-nets@main/TeachingNNs/network-builder/JS/plotly.js" = "Plotly"
